name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: 54.177.181.42
          username: root
          password: YRBENitB@{IXYwo?
          script: |
            cd /var/www/site/data/www/partners.financialmatch.com
            git pull
            npm run build
            pm2 restart partners.financialmatch.com